export const ADD_FRIENDS ='ADD_FRIENDS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const FETCHING_FRIENDS = "FETCHING_FRIENDS";
export const DONE_FETCHING_FRIENDS="DONE_FETCHING_FRIENDS";
export const FAILURE = "FAILURE";
